name: Sync Flickr data
env:
  DRY_RUN: yes

on: 
  workflow_dispatch:

jobs:
  post:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
        architecture: 'x64' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get updated photo database from Flickr
      env:
        FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
        FLICKR_API_SECRET: ${{ secrets.FLICKR_API_SECRET }}
        FLICKR_USER_ID: "191819781@N02"
        OUTFILE: "memories-whitehouse-raw-test.json"
      run: python ./tools/flickr_scrape.py

